import type { ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, CalendarDays, ChevronLeft, ChevronRight, CircleUserRound, Home, Info, Link2, LogIn, Megaphone, MessageCircleMore, MonitorPlay, Sparkles, UsersRound } from "lucide-react";
import { ScrollReveal } from "@/components/scroll-reveal";
import { SiteBrand } from "@/components/site-brand";
import { ThemeToggle } from "@/components/theme-toggle";
import { getCurrentUser } from "@/lib/auth/require-role";
import { getHomepagePublicContent, type SiteHomepageSection, type SiteNavigationIcon, type SiteNavigationItem } from "@/lib/data/phase8";

export default async function HomePage(){
  const [user,homepage]=await Promise.all([getCurrentUser(),getHomepagePublicContent()]);
  const {settings}=homepage;
  return <main className="site-page" id="home"><div className="site-ambient site-ambient-one"/><div className="site-ambient site-ambient-two"/>
    <header className="floating-header"><Link href="/" className="header-brand" aria-label={`${settings.header_site_name} หน้าหลัก`}><SiteBrand siteName={settings.header_site_name} tagline={settings.header_tagline} logoUrl={homepage.logoUrl} logoAlt={settings.header_logo_alt} showTagline={settings.header_show_tagline}/></Link><nav className="main-nav" aria-label="เมนูหลัก">{homepage.navigation.map(item=><NavigationLink key={item.id} item={item}/>)}</nav><div className="header-actions">{settings.header_show_theme_toggle?<ThemeToggle/>:null}<Link href={user?"/dashboard":"/login"} className="admin-button"><LogIn size={17}/>{user?settings.header_logged_in_label:settings.header_login_label}</Link></div></header>
    {homepage.sections.map(section=><HomepageSectionRenderer key={section.id} section={section} homepage={homepage}/>)}
    {settings.footer_is_visible?<footer className="site-footer"><div className="footer-glow"/><div className="footer-main"><div className="footer-brand"><SiteBrand siteName={settings.header_site_name} tagline={settings.header_tagline} logoUrl={homepage.logoUrl} logoAlt={settings.header_logo_alt} showTagline={settings.header_show_tagline}/><p>{settings.footer_description}</p></div><div><strong>{settings.footer_contact_heading}</strong>{settings.footer_contact_line_1?<p>{settings.footer_contact_line_1}</p>:null}{settings.footer_contact_line_2?<p>{settings.footer_contact_line_2}</p>:null}</div><div><strong>{settings.footer_social_heading}</strong><FooterLink label={settings.footer_facebook_label} href={settings.footer_facebook_url}/><FooterLink label={settings.footer_youtube_label} href={settings.footer_youtube_url}/><FooterLink label={settings.footer_line_label} href={settings.footer_line_url}/></div></div><div className="footer-bottom"><span>{settings.footer_copyright}</span>{settings.footer_technology?<span>{settings.footer_technology}</span>:null}</div></footer>:null}
  </main>;
}

type Homepage = Awaited<ReturnType<typeof getHomepagePublicContent>>;
function HomepageSectionRenderer({section,homepage}:{section:SiteHomepageSection;homepage:Homepage}){
  const className=`section-style-${section.background_style}`;
  switch(section.section_type){
    case "hero": return <HeroSection section={section} homepage={homepage}/>;
    case "roles": return <section className={`section role-section ${className}`} id={section.section_key}><SectionHeading section={section}/><div className="role-card-grid"><ScrollReveal><RoleCard icon={<MonitorPlay size={25}/>} title="ระบบสำหรับครู" description="จัดการชั้นเรียน เนื้อหา แบบฝึกหัด และติดตามผลการเรียนรู้" label="เข้าสู่ระบบครู" href="/login"/></ScrollReveal><ScrollReveal delay={110}><RoleCard icon={<CircleUserRound size={25}/>} title="ระบบสำหรับนักเรียน" description="เข้าเรียน ส่งงาน ทำแบบทดสอบ และตรวจสอบความก้าวหน้า" label="เข้าสู่ระบบนักเรียน" href="/login"/></ScrollReveal></div></section>;
    case "news": return <section className={`section news-section ${className}`} id={section.section_key}><SectionHeading section={section}/><div className="news-grid"><ScrollReveal><NewsCard date="22 ส.ค. 2569" title={`ยินดีต้อนรับสู่ ${homepage.settings.header_site_name}`} description="ศูนย์รวมการเรียนรู้ ข่าวสาร และกิจกรรมสำหรับครูและนักเรียน" pinned/></ScrollReveal><ScrollReveal delay={100}><NewsCard date="22 ส.ค. 2569" title="เปิดใช้งานระบบห้องเรียนออนไลน์" description="ครูและนักเรียนสามารถเข้าใช้งานผ่านระบบตามบทบาทได้แล้ว"/></ScrollReveal></div></section>;
    case "calendar": return <section className={`section calendar-section ${className}`} id={section.section_key}><SectionHeading section={section}/><div className="calendar-layout"><ScrollReveal className="calendar-card"><div className="calendar-heading"><button type="button" aria-label="เดือนก่อนหน้า"><ChevronLeft size={17}/></button><strong>สิงหาคม 2569</strong><button type="button" aria-label="เดือนถัดไป"><ChevronRight size={17}/></button></div><div className="calendar-weekdays">{["อา","จ","อ","พ","พฤ","ศ","ส"].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-days">{Array.from({length:35},(_,index)=>{const value=index<5?27+index:index-4;const muted=index<5||value>31;return <span key={index} className={`${muted?"muted":""} ${value===3&&!muted?"selected":""}`}>{value>31?value-31:value}</span>})}</div></ScrollReveal><ScrollReveal className="event-column" delay={120}><article className="event-card"><span className="event-icon"><CalendarDays size={21}/></span><div><small>กิจกรรมถัดไป</small><h3>อบรมการใช้งานระบบ {homepage.settings.header_site_name}</h3><p>22 ส.ค. 2569 · ห้องปฏิบัติการคอมพิวเตอร์</p></div></article><article className="event-card soft-event"><span className="event-icon"><UsersRound size={21}/></span><div><small>สำหรับนักเรียน</small><h3>เปิดชั้นเรียนประจำภาคเรียน</h3><p>ตรวจสอบรายวิชาและตารางเรียนผ่านระบบนักเรียน</p></div></article></ScrollReveal></div></section>;
    case "links": return <section className={`section links-section ${className}`} id={section.section_key}><SectionHeading section={section}/><div className="link-grid"><ScrollReveal><a className="useful-link" href="#home"><span><BookOpenCheck size={20}/></span><div><strong>คู่มือการใช้งาน</strong><small>รวมคู่มือสำหรับครูและนักเรียน</small></div><ArrowRight size={18}/></a></ScrollReveal><ScrollReveal delay={100}><a className="useful-link" href={contactHref(homepage.settings.footer_contact_line_2)}><span><MessageCircleMore size={20}/></span><div><strong>ติดต่อผู้ดูแลระบบ</strong><small>แจ้งปัญหาการใช้งานและขอความช่วยเหลือ</small></div><ArrowRight size={18}/></a></ScrollReveal></div></section>;
    case "cta": return <section className={`section phase82-custom-section phase82-cta ${className}`} id={section.section_key}><ScrollReveal><div className="phase82-custom-card"><SectionHeading section={section}/>{section.body?<p className="phase82-body">{section.body}</p>:null}{section.button_label&&section.button_url?<SmartLink href={section.button_url} className="button-primary">{section.button_label}<ArrowRight size={17}/></SmartLink>:null}</div></ScrollReveal></section>;
    default: return <section className={`section phase82-custom-section ${className}`} id={section.section_key}><ScrollReveal><div className="phase82-custom-card"><SectionHeading section={section}/>{section.body?<p className="phase82-body">{section.body}</p>:null}{section.button_label&&section.button_url?<SmartLink href={section.button_url} className="button-secondary">{section.button_label}</SmartLink>:null}</div></ScrollReveal></section>;
  }
}
function HeroSection({section,homepage}:{section:SiteHomepageSection;homepage:Homepage}){const s=homepage.settings;if(!s.hero_is_visible)return null;return <section className={`hero-section hero-mode-${s.hero_visual_mode} section-style-${section.background_style}`} id={section.section_key}><div className="hero-blue-shape"/><div className="hero-dot hero-dot-one"/><div className="hero-dot hero-dot-two"/><div className="hero-content">{s.hero_badge?<span className="hero-label"><Sparkles size={15}/>{s.hero_badge}</span>:null}<h1>{s.hero_title_primary}<span>{s.hero_title_accent}</span></h1><p>{s.hero_description}</p><div className="hero-buttons"><SmartLink href={s.hero_primary_url} className="button-primary">{s.hero_primary_label}<ArrowRight size={17}/></SmartLink><SmartLink href={s.hero_secondary_url} className="button-secondary">{s.hero_secondary_label}</SmartLink></div></div>{s.hero_visual_mode==="image"&&homepage.heroImageUrl?<div className="hero-image-zone"><div className="hero-image-halo"/><div className="hero-image-frame float-dashboard"><img src={homepage.heroImageUrl} alt={s.hero_image_alt}/></div><FloatingChips/></div>:null}{s.hero_visual_mode==="phone"?<PhoneHeroVisual siteName={s.header_site_name}/>:null}</section>}
function SectionHeading({section}:{section:SiteHomepageSection}){return <ScrollReveal className="section-title centered-title">{section.eyebrow?<span>{section.eyebrow}</span>:null}<h2>{section.title}</h2>{section.description?<p>{section.description}</p>:null}</ScrollReveal>}
function NavigationLink({item}:{item:SiteNavigationItem}){return <a href={safeHref(item.url)} target={item.open_new_tab?"_blank":undefined} rel={item.open_new_tab?"noreferrer noopener":undefined}><NavigationIcon name={item.icon_name}/>{item.label}</a>}
function NavigationIcon({name}:{name:SiteNavigationIcon}){const p={size:16};switch(name){case"home":return <Home {...p}/>;case"teacher":return <MonitorPlay {...p}/>;case"student":return <CircleUserRound {...p}/>;case"about":case"info":return <Info {...p}/>;case"book":return <BookOpenCheck {...p}/>;case"calendar":return <CalendarDays {...p}/>;case"megaphone":return <Megaphone {...p}/>;default:return <Link2 {...p}/>}}
function SmartLink({href,className,children}:{href:string;className:string;children:ReactNode}){const safe=safeHref(href);return safe.startsWith("/")?<Link href={safe} className={className}>{children}</Link>:<a href={safe} className={className}>{children}</a>}
function PhoneHeroVisual({siteName}:{siteName:string}){return <div className="hero-phone-zone" aria-label={`ตัวอย่าง ${siteName} Dashboard`}><div className="hero-phone-shadow"/><div className="hero-phone float-phone"><div className="phone-speaker"/><div className="phone-dashboard-card"><small>{siteName} Dashboard</small><strong>Welcome back!</strong><i/><i className="short"/></div><div className="phone-shortcuts"><span><BookOpenCheck size={17}/></span><span><CalendarDays size={17}/></span></div><div className="phone-progress-title"><strong>Learning progress</strong><b>72%</b></div><div className="phone-progress-track"><i/></div><div className="phone-lines"><i/><i/><i/></div></div><FloatingChips/></div>}
function FloatingChips(){return <><div className="floating-chip teacher-chip"><MonitorPlay size={18}/><span><small>สำหรับครู</small><strong>จัดการชั้นเรียน</strong></span></div><div className="floating-chip student-chip"><CircleUserRound size={18}/><span><small>สำหรับนักเรียน</small><strong>เรียนรู้ทันที</strong></span></div></>}
function FooterLink({label,href}:{label:string;href:string}){if(!label)return null;return <p>{href?<a href={safeHref(href)} target="_blank" rel="noreferrer noopener">{label}</a>:label}</p>}
function contactHref(value:string){const c=value.trim();return c.includes("@")?`mailto:${c}`:"#about"}
function safeHref(value:string){const h=value.trim();return h.startsWith("/")||h.startsWith("#")||h.startsWith("https://")||h.startsWith("http://")||h.startsWith("mailto:")||h.startsWith("tel:")?h:"#"}
function RoleCard({icon,title,description,label,href}:{icon:ReactNode;title:string;description:string;label:string;href:string}){return <article className="role-card"><div className="role-card-corner"/><span className="role-icon">{icon}</span><h3>{title}</h3><p>{description}</p><Link href={href}>{label}<ArrowRight size={17}/></Link></article>}
function NewsCard({date,title,description,pinned=false}:{date:string;title:string;description:string;pinned?:boolean}){return <article className="news-card"><div className="news-cover">{pinned?<span>ปักหมุด</span>:null}<Megaphone size={34}/></div><div className="news-content"><small>{date}</small><h3>{title}</h3><p>{description}</p><a href="#news">อ่านรายละเอียด<ArrowRight size={16}/></a></div></article>}
