-- TK Mooc Phase 8.4
begin;
do $$ begin if not exists (select 1 from pg_type where typname='site_publish_status') then create type public.site_publish_status as enum ('draft','scheduled','published','archived'); end if; end $$;
create table if not exists public.site_content_revisions(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid,action_type text not null,version_number integer not null default 1,snapshot jsonb not null default '{}'::jsonb,change_note text,changed_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create index if not exists idx_site_content_revisions_entity on public.site_content_revisions(entity_type,entity_id,version_number desc);
create table if not exists public.site_preview_sessions(id uuid primary key default gen_random_uuid(),token_hash text not null unique,created_by uuid not null references public.profiles(id) on delete cascade,expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now());
do $$ declare t text; begin foreach t in array array['site_homepage_settings','site_navigation_items','site_homepage_sections','site_news_items','site_events','site_stat_items','site_related_links'] loop execute format('alter table public.%I add column if not exists publish_status public.site_publish_status not null default %L',t,'published'); execute format('alter table public.%I add column if not exists scheduled_at timestamptz',t); execute format('alter table public.%I add column if not exists published_at timestamptz',t); execute format('alter table public.%I add column if not exists archived_at timestamptz',t); end loop; end $$;
create or replace function public.site_record_revision(target_entity_type text,target_entity_id uuid,target_action_type text,target_snapshot jsonb,target_change_note text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v integer; rid uuid; begin if not public.is_admin() then raise exception 'admin role required'; end if; select coalesce(max(version_number),0)+1 into v from public.site_content_revisions where entity_type=target_entity_type and entity_id is not distinct from target_entity_id; insert into public.site_content_revisions(entity_type,entity_id,action_type,version_number,snapshot,change_note,changed_by) values(target_entity_type,target_entity_id,target_action_type,v,coalesce(target_snapshot,'{}'::jsonb),target_change_note,auth.uid()) returning id into rid; return rid; end $$;
grant execute on function public.site_record_revision(text,uuid,text,jsonb,text) to authenticated;
alter table public.site_content_revisions enable row level security; alter table public.site_preview_sessions enable row level security;
drop policy if exists "admins manage revisions" on public.site_content_revisions; create policy "admins manage revisions" on public.site_content_revisions for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admins manage preview sessions" on public.site_preview_sessions; create policy "admins manage preview sessions" on public.site_preview_sessions for all to authenticated using(public.is_admin()) with check(public.is_admin());
insert into public.system_settings(setting_key,setting_value,is_public) values('schema_version','"8.4.0"'::jsonb,true) on conflict(setting_key) do update set setting_value=excluded.setting_value,updated_at=now();
commit;
