import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Eye, Plus, Save, Trash2 } from "lucide-react";
import { saveNewsAction, deleteNewsAction } from "@/app/phase83-actions";
import { requireRole } from "@/lib/auth/require-role";
import { getPhase83AdminData } from "@/lib/data/phase8";
export const metadata:Metadata={title:"จัดการข่าวสาร | TK Mooc"};
type Props={searchParams:Promise<{saved?:string;error?:string}>};
export default async function Page({searchParams}:Props){await requireRole("admin");const feedback=await searchParams;let rows:any[]=[];try{rows=await getPhase83AdminData("site_news_items") as any[]}catch(e){return <ErrorBox message={e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ"}/>}return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-blue-900 to-sky-500 p-7 text-white shadow-xl"><div className="flex flex-wrap justify-between gap-4"><div><span className="text-xs font-black tracking-[.22em] text-blue-100">PHASE 8.3 · PUBLIC CONTENT</span><h1 className="mt-3 text-4xl font-black">จัดการข่าวสาร</h1><p className="mt-2 text-blue-100">เพิ่ม แก้ไข ซ่อน และจัดลำดับข้อมูลที่แสดงบนหน้าหลัก</p></div><div className="flex gap-2"><Link href="/admin/content/sections" className="rounded-full border border-white/25 px-4 py-2 font-bold"><ArrowLeft size={16} className="inline"/> Section</Link><Link href="/" target="_blank" className="rounded-full border border-white/25 px-4 py-2 font-bold"><Eye size={16} className="inline"/> ดูหน้าหลัก</Link></div></div></header>{feedback.saved?<Notice good text={feedback.saved}/>:null}{feedback.error?<Notice text={feedback.error}/>:null}<section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><Plus/> เพิ่มรายการใหม่</h2><div className="mt-5"><ItemForm/></div></section><section className="space-y-4">{rows.map(row=><article key={row.id} className="rounded-3xl border bg-white p-6 shadow-sm"><ItemForm row={row}/><form action={deleteNewsAction} className="mt-3"><input type="hidden" name="id" value={row.id}/><button className="inline-flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 font-bold text-rose-700"><Trash2 size={16}/> ลบ</button></form></article>)}</section></div></main>}
function ItemForm({row}:{row?:any}){return <form action={saveNewsAction} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={row?.id??""}/><Field label="หัวข้อข่าว"><input name="title" type="text" defaultValue={row?.title??""} className="input"/></Field><Field label="คำโปรย"><textarea name="summary" defaultValue={row?.summary??""} rows={3} className="input"/></Field><Field label="รายละเอียด"><textarea name="content" defaultValue={row?.content??""} rows={3} className="input"/></Field><Field label="ลิงก์ภายนอก"><input name="externalUrl" type="text" defaultValue={row?.external_url??""} className="input"/></Field><Field label="วันเวลาเผยแพร่"><input name="publishedAt" type="datetime-local" defaultValue={formatLocal(row?.published_at)} className="input"/></Field><Field label="วันเวลาสิ้นสุด"><input name="expiresAt" type="datetime-local" defaultValue={formatLocal(row?.expires_at)} className="input"/></Field><Field label="ลำดับ"><input name="displayOrder" type="number" defaultValue={row?.display_order??100} className="input"/></Field><div className="flex flex-wrap items-center gap-5"><label className="flex items-center gap-2 font-bold"><input type="checkbox" name="isPinned" defaultChecked={row?row.is_pinned:true}/> ปักหมุด</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" name="isVisible" defaultChecked={row?row.is_visible:true}/> แสดงบนหน้าหลัก</label></div><div className="text-right"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-black text-white"><Save size={17}/> {row?"บันทึกการแก้ไข":"เพิ่มรายการ"}</button></div></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-2 text-sm font-bold"><span>{label}</span>{children}</label>}
function Notice({text,good=false}:{text:string;good?:boolean}){return <div className={`rounded-2xl border px-5 py-4 font-bold ${good?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-rose-200 bg-rose-50 text-rose-800"}`}>{text}</div>}
function ErrorBox({message}:{message:string}){return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="rounded-3xl border bg-white p-8"><h1 className="text-2xl font-black">ต้องติดตั้ง Phase 8.3</h1><p className="mt-3">{message}</p><code className="mt-4 block bg-slate-950 p-4 text-white">supabase/migrations/0010_phase8_3_public_content.sql</code></div></main>}
function formatLocal(value?:string){if(!value)return "";const d=new Date(value);return Number.isNaN(d.getTime())?"":new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
